### ISSUE TITLE
建議將「簡體中文」改成「簡化字」

### ISSUE THREAD

**Issue by IanHo79** [missing-semester-zh-Hant/missing-semester-zh-Hant.github.io#8]
建議將「簡體中文」改成「簡化字」
參考資料：
https://zh.wikipedia.org/zh-tw/簡化字

**Comment by goodjack** [comment]
不同意，意義不同
前者是指用字文化，後者僅代表寫法

**Comment by IanHo79** [comment]
> 不同意，意義不同
> 前者是指用字文化，後者僅代表寫法

「中共」的「官方用詞」就是「簡化字」。

**Comment by Mion354D** [comment]
Done.
